kafka:
  address: ${ZG_KAFKA_ADDRESS}
  group_id: sql_repo
  user: guest
  password: guest
  topic: processing_1

dbs:
  - host: ${MYSQL_DB_1_HOST}
    port: ${MYSQL_DB_1_PORT}
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    migrations_path: ./db/migrations

  - host: ${MYSQL_DB_2_HOST}
    port: ${MYSQL_DB_2_PORT}
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    migrations_path: ./db/migrations

cache:
  address: ${ZG_REDIS_ADDRESS}
  db: ${ZG_REDIS_CACHE_DB}
  exp_time: ${ZG_REDIS_EXP_TIME}

kvdb:
  address: ${ZG_REDIS_ADDRESS}
  db: ${ZG_REDIS_DB}

logstash:
    url: ${LOGSTASH_URL}