telemetry:
  enabled: true
  interval: 10
  address: localhost:8888

kafka:
  address: ${ZG_KAFKA_ADDRESS}
  group_id: sql_repo
  user: guest
  password: guest
  topic: processing_1

dbs:
  - port: ${MYSQL_DB_1_PORT}
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  - port: ${MYSQL_DB_2_PORT}
    database: ${MYSQL_DATABASE}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

cache:
  address: ${ZG_REDIS_ADDRESS}
  db: ${ZG_REDIS_DB}
  exp_time: ${ZG_REDIS_EXP_TIME}
