telemetry:
  enabled: true
  interval: 10
  address: localhost:8888

kafka:
  address: ${ZG_KAFKA_ADDRESS}
  group_id: sql_repo
  user: guest
  password: guest
  topic: processing_1

dbs:
  mysqldbs:
    - ${MYSQL_DB_1_PORT}
    - ${MYSQL_DB_2_PORT}
  mysqlcreds:
    - ${MYSQL_DATABASE}
    - ${MYSQL_USER}
    - ${MYSQL_PASSWORD}

redis:
  address: ${ZG_REDIS_ADDRESS}
  db: ${ZG_REDIS_DB}
