version: '3'

networks:
  local-net:
    external: true

services:

#  zg_sql_repo:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: zg_sql_repo
#    env_file:
#      - .env-docker
#    networks:
#      - local-net
#    volumes:
#      - .:/app
#    depends_on:
#      - zg_redis_cache
#      - zg_mysql_db_1
#      - zg_mysql_db_2

  zg_sql_repo_redis:
    image: redis:latest
    container_name: zg_sql_repo_redis
    ports:
      - '16379:6379'
    networks:
      - local-net

  zg_mysql_db_1:
    image: mysql:5.7
    container_name: zg_mysql_db_1
    env_file:
      - .env-docker
    ports:
      - "${MYSQL_DB_1_PORT}:3306"
    volumes:
      - mysql_db_1_data:/var/lib/mysql
    networks:
      - local-net

  zg_mysql_db_2:
    image: mysql:5.7
    container_name: zg_mysql_db_2
    env_file:
      - .env-docker
    ports:
      - "${MYSQL_DB_2_PORT}:3306"
    volumes:
      - mysql_db_2_data:/var/lib/mysql
    networks:
      - local-net

volumes:
  mysql_db_1_data:
  mysql_db_2_data:

