version: '3'

networks:
  local-net:
    external: true

services:

#  zg_sql_repo:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: zg_sql_repo
#    env_file:
#      - .env-docker
#    networks:
#      - local-net
#    volumes:
#      - .:/app
#    depends_on:
#      - zg_mongodb

  zg_redis:
    image: redis:latest
    container_name: zg_redis
    ports:
      - '6379:6379'
    networks:
      - local-net

volumes:
  mongodbdata:

